### ISSUE TITLE
is_comment_block() should also take care of `#` comments

### ISSUE THREAD

**Issue by 3D-I** [battye/php-array-parser#2]
https://github.com/battye/php-array-parser/blob/9927b2985b7b45d1e4ff516650850e8c14fa9f69/src/parser.php#L204

`#` can also be a comment.

Ie.:

```php
# Option 1
# Option 2
# Option 3
```

**Comment by battye** [comment]
Thank you for finding this @3D-I, that was well spotted. I've created a fix which I'll merge in soon - I just need to figure out how to replace the obsolete Travis CI with the new GitHub Actions while I'm at it! 😄
